sonata_admin:
  title: 'Api Symfony'
  dashboard:
    blocks:
      - { type: sonata.admin.block.admin_list, position: left }
    groups:
      admin:
        label: Administrador
        icon: <i class="fa fa-pencil"></i>
  global_search:
    empty_boxes: fade
    admin_route: edit

sonata_block:
  blocks:
    sonata.admin.block.admin_list:
      contexts: [ admin ]
